version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=teto-postgres
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - .:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: .
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 8080:8080
    volumes:
      - .:/app